// <auto-generated />
 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WineSite.Data.Data;

#nullable disable

namespace WineSite.Data.Migrations
{
    [DbContext(typeof(WineShopDbContext))]
    [Migration("20240316073717_Initial")]
    partial class Initial  
    {
    }
}
