// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
 
using Microsoft.EntityFrameworkCore.Migrations;
 
using WineSite.Data.Data;

#nullable disable

namespace WineSite.Data.Migrations
{
    [DbContext(typeof(WineShopDbContext))]
    [Migration("20240325145303_AddedAdmin")]
    partial class AddedAdmin 
    {
    }
}
